# Change baseurl before deploy
baseurl = "https://zack.zip"
locale = "en-us"
title = "Zack Dot Zip"
defaultContentLanguage = "en"
hasCJKLanguage = false
enableRobotsTXT = true

[pagination]
pagerSize = 6
